name: open_ai
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/pradyotprksh/development_learning.git

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  http: ^0.13.5

  logger: ^1.2.2

dev_dependencies:
  lints: ^2.0.1

  test: ^1.23.1
