name: stackexchange_api
description: A dart SDK to connect to StackExchange apis https://api.stackexchange.com/docs
version: 1.0.0
homepage: https://api.stackexchange.com/docs

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  http: ^0.13.3

  logger: ^1.0.0

dev_dependencies:
  test: any

  flutter_lints: ^1.0.0