name: second_hand_clothes
description: A flutter project which will be used to sell/buy second hand clothes.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0

  cached_network_image: ^3.2.0

  cloud_firestore: ^3.1.10

  connectivity_plus: ^2.2.1

  cupertino_icons: ^1.0.2

  device_info_plus: ^3.2.2

  enum_to_string: ^2.0.1

  firebase_analytics: ^9.1.2

  firebase_auth: ^3.3.11

  firebase_core: ^1.13.1

  firebase_crashlytics: ^2.5.3

  firebase_dynamic_links: ^4.1.1

  firebase_performance: ^0.8.0+7

  firebase_storage: ^10.2.9

  flex_color_scheme: ^4.2.0

  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.1

  get_ip_address: ^0.0.5

  google_fonts: ^2.3.1

  hydrated_bloc: ^8.1.0

  image_picker: ^0.8.4+11

  intl: ^0.17.0

  logger: ^1.1.0

  replay_bloc: ^0.2.1

  share_plus: ^4.0.1

dev_dependencies:
  bloc_test: ^9.0.3

  flutter_lints: ^1.0.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
