name: second_hand_clothes
description: A flutter project which will be used to sell/buy second hand clothes.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0

  cached_network_image: ^3.2.1

  cloud_firestore: ^3.1.16

  connectivity_plus: ^2.3.0

  cupertino_icons: ^1.0.4

  device_info_plus: ^3.2.3

  email_validator: ^2.0.1

  enum_to_string: ^2.0.1

  equatable: ^2.0.3

  firebase_analytics: ^9.1.8

  firebase_auth: ^3.3.18

  firebase_core: ^1.17.0

  firebase_crashlytics: ^2.8.0

  firebase_database: ^9.0.14

  firebase_dynamic_links: ^4.2.4

  firebase_performance: ^0.8.0+12

  firebase_storage: ^10.2.16

  flex_color_scheme: ^5.0.1

  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.1

  flutter_localizations:
    sdk: flutter

  formz: ^0.4.1

  get_ip_address: ^0.0.5

  google_fonts: ^3.0.1

  hydrated_bloc: ^8.1.0

  image_picker: ^0.8.5+3

  intl: ^0.17.0

  logger: ^1.1.0

  lottie: ^1.3.0

  material_design_icons_flutter: ^5.0.6595

  password_strength: ^0.2.0

  path_provider: ^2.0.10

  replay_bloc: ^0.2.1

  share_plus: ^4.0.4

dev_dependencies:
  bloc_test: ^9.0.3

  flutter_lints: ^2.0.1

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/
    - assets/form/
    - assets/lottie/
