name: pet_perfect_assignemnt
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1

  cupertino_icons: ^1.0.5

  dio: ^4.0.6

  equatable: ^2.0.3

  flex_color_scheme: ^5.0.1

  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.1

  google_fonts: ^3.0.1

  hive: ^2.2.3

  json_annotation: ^4.5.0

  logger: ^1.1.0

  mime: ^1.0.2

  video_player: ^2.4.5

dev_dependencies:
  bloc_test: ^9.0.3

  build_runner: ^2.1.11

  flutter_lints: ^2.0.1

  flutter_test:
    sdk: flutter

  json_serializable: ^6.2.0

flutter:

  uses-material-design: true

  assets:
    - assets/