name: fews
description: An application which connects to https://www.thenewsapi.com/ api and show the news.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3

  cupertino_icons: ^1.0.5

  equatable: ^2.0.5

  flex_color_scheme: ^7.1.2

  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3

  flutter_localizations:
    sdk: flutter

  google_fonts: ^4.0.4

  intl: any

  json_annotation: ^4.8.1

  logger: ^1.4.0

  retrofit: 4.0.1

dev_dependencies:
  bloc_test: ^9.1.3

  build_runner: ^2.4.5

  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.1

  flutter_test:
    sdk: flutter

  json_serializable: ^6.7.0

  retrofit_generator: ^7.0.1+1

flutter:

  uses-material-design: true

  generate: true

  assets:
    - assets/

flutter_icons:
  image_path: 'assets/app_icon.png'
  android: true
  ios: true
  remove_alpha_ios: true
