name: whatsapp
description: A WhatsApp clone using Flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  auto_size_text: ^3.0.0

  cache_video_player: ^0.0.4

  cached_network_image: ^3.2.3

  camera: ^0.10.5+2

  camerawesome: ^1.4.0

  clipboard: ^0.1.3

  cloud_firestore: ^4.8.1

  collection: ^1.17.1

  connectivity_plus: ^4.0.1

  contacts_service: ^0.6.3

  cupertino_icons: ^1.0.5

  device_info_plus: ^8.2.1

  email_validator: ^2.1.17

  emoji_picker_flutter: ^1.5.4

  enum_to_string: ^2.0.1

  equatable: ^2.0.5

  fast_cached_network_image: ^1.2.0

  file_picker: ^5.3.0

  filesize: ^2.0.1

  firebase_analytics: ^10.4.3

  firebase_app_check: ^0.1.4+3

  firebase_auth: ^4.6.3

  firebase_core: ^2.14.0

  firebase_crashlytics: ^3.3.3

  firebase_dynamic_links: ^5.3.3

  firebase_performance: ^0.9.2+3

  firebase_remote_config: ^4.2.3

  firebase_storage: ^11.2.3

  firebase_ui_auth: ^1.4.3

  flex_color_scheme: ^7.1.2

  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3

  flutter_colorpicker: ^1.0.3

  flutter_fgbg: ^0.2.2

  flutter_image_compress: ^2.0.3

  flutter_link_previewer: ^3.2.1

  flutter_linkify: ^6.0.0

  flutter_localizations:
    sdk: flutter

  fluttermoji: ^1.0.2

  get_ip_address: ^0.0.5

  google_fonts: ^4.0.4

  hydrated_bloc: ^9.1.1

  image_cropper: ^4.0.1

  image_picker: ^0.8.9

  installer_info: ^0.5.0

  liquid_swipe: ^3.1.0

  local_auth: ^2.1.6

  logger: ^1.4.0

  network_info_plus: ^4.0.1

  package_info_plus: ^4.0.2

  path_provider: ^2.0.15

  pdf_manipulator: ^0.5.9

  permission_handler: ^10.3.0

  pinput: ^2.2.31

  qr_code_scanner: ^1.0.1

  qr_flutter: ^4.1.0

  replay_bloc: ^0.2.4

  screenshot_callback:
    git:
      url: https://github.com/pradyotprksh/flutter_screenshot_callback.git
      ref: project-upgrade

  step_progress_indicator: ^1.0.2

  stop_watch_timer: ^2.0.0

  syncfusion_flutter_pdfviewer: ^21.2.10

  timeago: ^3.4.0

  url_launcher: ^6.1.11

  video_compress: ^3.1.2

  video_player: ^2.6.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/

flutter_icons:
  image_path: 'assets/whatsapp.png'
  android: true
  ios: true
  remove_alpha_ios: true