name: whatsapp
description: A WhatsApp clone using Flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  auto_size_text: ^3.0.0

  cached_network_image: ^3.2.3

  cloud_firestore: ^4.3.1

  connectivity_plus: ^3.0.2

  cupertino_icons: ^1.0.5

  device_info_plus: ^8.0.0

  email_validator: ^2.1.17

  encrypt: ^5.0.1

  enum_to_string: ^2.0.1

  equatable: ^2.0.5

  firebase_analytics: ^10.1.0

  firebase_app_check: ^0.1.1+8

  firebase_auth: ^4.2.5

  firebase_core: ^2.4.1

  firebase_crashlytics: ^3.0.10

  firebase_dynamic_links: ^5.0.11

  firebase_performance: ^0.9.0+10

  firebase_storage: ^11.0.10

  firebase_ui_auth: ^1.1.8

  flex_color_scheme: ^6.1.2

  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.1

  flutter_localizations:
    sdk: flutter

  get_ip_address: ^0.0.5

  google_fonts: ^3.0.1

  hydrated_bloc: ^9.0.0

  image_cropper: ^3.0.1

  image_picker: ^0.8.6

  liquid_swipe: ^3.0.0

  logger: ^1.1.0

  network_info_plus: ^3.0.1

  package_info_plus: ^3.0.2

  path_provider: ^2.0.11

  pin_code_fields: ^7.4.0

  replay_bloc: ^0.2.2

dev_dependencies:
  bloc_test: ^9.1.0

  flutter_launcher_icons: ^0.11.0

  flutter_lints: ^2.0.1

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/

flutter_icons:
  image_path: 'assets/whatsapp.png'
  android: true
  ios: true
  remove_alpha_ios: true