name: whatsapp
description: A WhatsApp clone using Flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  auto_size_text: ^3.0.0

  cache_video_player: ^0.0.4

  cached_network_image: ^3.2.3

  camerawesome: ^1.2.1

  cloud_firestore: ^4.3.1

  collection: ^1.17.0

  connectivity_plus: ^3.0.2

  contacts_service: ^0.6.3

  cupertino_icons: ^1.0.5

  device_info_plus: ^8.0.0

  email_validator: ^2.1.17

  encrypt: ^5.0.1

  enum_to_string: ^2.0.1

  equatable: ^2.0.5

  firebase_analytics: ^10.1.0

  firebase_app_check: ^0.1.1+8

  firebase_auth: ^4.2.5

  firebase_core: ^2.4.1

  firebase_crashlytics: ^3.0.11

  firebase_dynamic_links: ^5.0.11

  firebase_performance: ^0.9.0+10

  firebase_remote_config: ^3.0.9

  firebase_storage: ^11.0.10

  firebase_ui_auth: ^1.1.9

  flex_color_scheme: ^6.1.2

  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.2

  flutter_colorpicker: ^1.0.3

  flutter_image_compress: ^1.1.3

  flutter_localizations:
    sdk: flutter

  get_ip_address: ^0.0.5

  google_fonts: ^4.0.3

  hydrated_bloc: ^9.1.0

  image_cropper: ^3.0.1

  image_picker: ^0.8.6+1

  liquid_swipe: ^3.0.0

  logger: ^1.1.0

  memory_cache: ^1.2.0

  network_info_plus: ^3.0.1

  package_info_plus: ^3.0.2

  path_provider: ^2.0.12

  permission_handler: ^10.2.0

  pin_code_fields: ^7.4.0

  qr_code_scanner: ^1.0.1

  qr_flutter: ^4.0.0

  replay_bloc: ^0.2.3

  step_progress_indicator: ^1.0.2

  stop_watch_timer: ^2.0.0

  timeago: ^3.3.0

  url_launcher: ^6.1.9

  video_compress: ^3.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.11.0

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/

flutter_icons:
  image_path: 'assets/whatsapp.png'
  android: true
  ios: true
  remove_alpha_ios: true