on:
  push:
    branches:
      - main
    paths:
      - android/**
name: Android Projects
jobs:
  algorithms:
    name: Rental Code Checker
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Checking Rental
        working-directory: ./android/Rental
        run: |
          ./gradlew lint
          ./gradlew build