on:
  push:
    branches:
      - main
    paths:
      - dart/**
name: Dart Projects
jobs:
  interview_preparation:
    name: interview_preparation Code Checker
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: dart-lang/setup-dart@v1
      - name: Checking interview_preparation
        working-directory: ./dart/interview_preparation
        run: |
          dart pub get
          dart analyze
  algorithms:
    name: algorithms Code Checker
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: dart-lang/setup-dart@v1
      - name: Checking algorithms
        working-directory: ./dart/algorithms
        run: |
          dart pub get
          dart analyze
  data_structures:
    name: data_structures Code Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: dart-lang/setup-dart@v1
      - name: Checking data_structures
        working-directory: ./dart/data_structures
        run: |
          dart pub get
          dart analyze
  stackexchange_api:
    name: stackexchange_api Code Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: dart-lang/setup-dart@v1
      - name: Checking stackexchange_api
        working-directory: ./dart/stackexchange_api
        run: |
          dart pub get
          dart analyze
          dart test
          dart pub publish --dry-run