on:
  push:
    branches:
      - main
name: Flutter/Dart Projects
jobs:
  flublog:
    name: flublog Code Checker
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
      - run: flutter doctor
      - name: Checking flublog
        working-directory: ./flutter/flublog
        run: |
          flutter clean
          flutter pub get
          flutter analyze
  stackexchange_api:
    name: stackexchange_api Code Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: dart-lang/setup-dart@v1
      - name: Checking stackexchange_api
        working-directory: ./dart/stackexchange_api
        run: |
          dart pub get
          dart analyze
          dart test
          dart pub publish --dry-run
  stackoverflow:
    name: stackoverflow Code Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
      - run: flutter doctor
      - name: Checking stackoverflow
        working-directory: ./flutter/stackoverflow
        run: |
          flutter clean
          flutter pub get
          flutter analyze
  second_hand_clothes:
    name: second_hand_clothes Code Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
      - run: flutter doctor
      - name: Checking second_hand_clothes
        working-directory: ./flutter/second_hand_clothes
        run: |
          flutter clean
          flutter pub get
          flutter analyze