on:
  push:
    branches:
      - main
    paths:
      - go/**
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
name: Go Projects
jobs:
  learning:
    name: learning Code Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go/learning/hello/go.mod'
      - run: go version
      - name: Checking greetings
        working-directory: ./go/learning/greetings
        run: go test
      - name: Checking hello
        working-directory: ./go/learning/hello
        run: go run .
      - name: Checking workspace
        working-directory: ./go/learning/workspace
        run: go run pradyot.com/hello
      - name: Checking example
        working-directory: ./go/learning/workspace/example
        run: go test ./...
      - name: Checking web-service-gin
        working-directory: ./go/learning/web-service-gin
        run: |
          go run .
          curl http://localhost:8080/albums
          curl http://localhost:8080/albums \
            --include \
            --header "Content-Type: application/json" \
            --request "POST" \
            --data '{"id": "4","title": "The Modern Sound of Betty Carter","artist": "Betty Carter","price": 49.99}'
          curl http://localhost:8080/albums/4
