on:
  push:
    branches:
      - main
    paths:
      - go/**
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
name: Go Projects
jobs:
  hello:
    name: learning Code Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go/learning/hello/go.mod'
      - run: go version
      - name: Checking learning
        working-directory: ./go/learning/hello
        run: go run .
