on:
  push:
    branches:
      - main
    paths:
      - KotlinMultiplatform/**
name: Android Projects
jobs:
  TheMovieDBKMM:
    name: TheMovieDBKMM Code Checker
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
          distribution: 'adopt'
          cache: gradle
      - name: Checking TheMovieDBKMM
        working-directory: ./KotlinMultiplatform/TheMovieDBKMM
        run: |
          chmod +x ./gradlew
          ./gradlew lint
          ./gradlew build
  KotlinMultiplatformSandbox:
    name: KotlinMultiplatformSandbox Code Checker
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
          distribution: 'adopt'
          cache: gradle
      - name: Checking KotlinMultiplatformSandbox
        working-directory: ./KotlinMultiplatform/KotlinMultiplatformSandbox
        run: |
          chmod +x ./gradlew
          ./gradlew lint
          ./gradlew build
