on:
  push:
    branches:
      - main
    paths:
      - python/**
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
name: Python Projects
jobs:
  renter:
    name: renter Code Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ricardochaves/python-lint@master
        with:
          python-root-list: "python/renter"
  programming:
    name: programming Code Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ricardochaves/python-lint@master
        with:
          python-root-list: "python/programming"
  pyblog:
    name: pyblog Code Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ricardochaves/python-lint@master
        with:
          python-root-list: "python/pyblog"
  pythonBootcamp:
    name: renter Code Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ricardochaves/python-lint@master
        with:
          python-root-list: "python/UdemyCourse/2022_Python_Bootcamp"