on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
name: Python Projects
jobs:
  practice:
    name: practice Code Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ricardochaves/python-lint@master
        with:
          python-root-list: "python/practice"
  pyblog:
    name: pyblog Code Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ricardochaves/python-lint@master
        with:
          python-root-list: "python/pyblog"